name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        dotnet build
    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: myapp.exe
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: myapp
